proxies/sandbox/Makefile, proxies/sandbox/apiproxy/ambulance.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddAsidHeader.xml, proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml, proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetAsid.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BadRequest.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/targets/sandbox.xml
=> AMB-56 add sandbox proxy

azure-pipelines.yml
=> AMB-56 match artifact name with alias

proxies/sandbox/apiproxy/proxies/default.xml
=> AMB-90 apply auth for all endpoints

.github/workflows/continous-integration-workflow.yaml
=> AMB-116 add continous-integration-workflow.yaml file

proxies/live/apiproxy/policies/AssignMessage.BadApiKeyErrorResponse.xml, proxies/live/apiproxy/policies/AssignMessage.NoApiKeyErrorResponse.xml, proxies/live/apiproxy/policies/ExtractVariables.VerifyApiKeyFaultString.xml, proxies/live/apiproxy/policies/RaiseFault.MethodNotAllowed.xml, proxies/live/apiproxy/targets/apim.xml, proxies/sandbox/apiproxy/policies/AssignMessage.BadApiKeyErrorResponse.xml, proxies/sandbox/apiproxy/policies/AssignMessage.NoApiKeyErrorResponse.xml, proxies/sandbox/apiproxy/policies/ExtractVariables.VerifyApiKeyFaultString.xml, proxies/sandbox/apiproxy/policies/RaiseFault.MethodNotAllowed.xml, proxies/sandbox/apiproxy/targets/apim.xml
=> AMB-135 added policies for no/invalid API keys

proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/targets/apim.xml
=> removed unattended access

azure-pipelines.yml
=> added sandbox to ecs deployment

proxies/sandbox/apiproxy/policies/VerifyAccessToken.xml, proxies/sandbox/apiproxy/targets/apim.xml
=> Amb 189 remove auth policy

package-lock.json, package.json, specification/ambulance-analytics.yaml, specification/components/examples/dataset-id.json, specification/components/examples/x-dataset-id.json, specification/components/schemas/dataset-id.yaml
=> Amb 00 fix spec

Makefile, tests/e2e/ambulance-analytics-sandbox.json
=> Amb 00 fix postman tests

.github/workflows/pr-lint.yaml, azure/project.yml
=> Remove "API" and Product description

azure/azure-release-pipeline.yml
=> explicit product availability

proxies/live/apiproxy/policies/RaiseFault.ServerNotFound.xml, proxies/live/apiproxy/targets/dps.xml, tests/e2e/ambulance_analytics.json
=> validation for dps url

.gitignore, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/templates/tests.yml, tests/.gitignore, tests/e2e/environments/internal-dev.postman.json
…ine secrets because azure devops can't export multiline variables
=> AMB-266 add automated postman tests

azure/azure-release-pipeline.yml
=> AMB-266 remove tests from internal-qa

Makefile
=> AMB-325 remove generate examples because there's no example anymore

azure/azure-release-pipeline.yml
=> AMB-325 Enabled prod build target

azure/azure-release-pipeline.yml
=> AMB-325 Fixed incorrect proxy_path

specification/ambulance-analytics.yaml
=> AMB-335 fix spec - address points in the ticket

azure/azure-pr-pipeline.yml, specification/ambulance-analytics.yaml
=> AMB-348 try this api sandbox bug

specification/ambulance-analytics.yaml
=> AMB-360 change claims to lowercase

proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml, tests/e2e/ambulance_analytics.json
=> AMB-456 add Content-Type header to _ping

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/templates/tests.yml
=> apm-1351: aws build agents temporary pinned utils

azure/templates/smoke-tests.yml
=> apm-1351: need to assume role to access prod parameters

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml, proxies/live/apiproxy/proxies/default.xml
=> AMB-506 Added splunk logging

azure/azure-release-pipeline.yml, proxies/live/apiproxy/policies/VerifyApiKey-Header.xml, proxies/live/apiproxy/proxies/default.xml
=> Removed status monitoring endpoint and added disable_status flag

proxies/live/apiproxy/policies/AssignMessage.SetStatusResponse.xml, proxies/live/apiproxy/policies/JS.SetStatusResponse.xml, proxies/live/apiproxy/policies/Javascript.SetStatusResponse.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetSharedSecureVariables.xml, proxies/live/apiproxy/policies/RaiseFault.403Forbidden.xml, proxies/live/apiproxy/resources/jsc/setStatusResponse.js, proxies/live/apiproxy/targets/dps.xml
=> AMB-468 add _status endpoint

azure/azure-release-pipeline.yml
=> AMB-468 remove disable_status_monitoring flag

proxies/sandbox/apiproxy/policies/KeyValueMapOperations.GetSharedSecureVariables.xml, proxies/sandbox/apiproxy/policies/RaiseFault.401Unauthorized.xml, proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml, proxies/sandbox/apiproxy/policies/javascript.SetStatusResponse.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/resources/jsc/SetStatusResponse.js
=> AMB-468 add _status endpoint to sandbox

proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml, proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml, proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/setStatusResponse.js, proxies/live/apiproxy/targets/dps.xml
=> AMB-534 Update _status output

specification/ambulance-analytics.yaml
=> AMB-539 update spec with client_id requirement

manifest_template.yml
This PR adds a manifest_template.yml file, which controls how the pipeline creates products/specs/api catalog entries.
=> APM-1572 Add manifest file

azure/project.yml, specification/ambulance-analytics.yaml
rename base path and product display name
=> AMB-552 Rename base-path to ambulance-data-submission

docker/ambulance-analytics-sandbox/src/routes/postAmbulanceData.js, proxies/live/apiproxy/targets/dps.xml, specification/ambulance-analytics.yaml, tests/e2e/ambulance-analytics-sandbox.json, tests/e2e/ambulance_analytics.json
=> AMB-494 rename /submission to /$process-message

tests/e2e/ambulance_analytics.json
=> AMB-507 Fix broken test

manifest_template.yml, proxies/live/apiproxy/policies/FlowCallout.ApplyRateLimiting.xml, proxies/live/apiproxy/targets/dps.xml
Added rate-limiting thru the new platform rate limit shared flow
=> AMB-866 add rate limiting sharedflow

azure/templates/smoke-tests.yml
=> AMB-892 fix failing smoke tests

.github/workflows/pr-lint.yaml, specification/ambulance-analytics.yaml
=> Adz 1590 update service level

specification/ambulance-analytics.yaml
=> Formatted service level section

specification/ambulance-analytics.yaml
=> AMB-1075 specify the API is in public Beta

specification/ambulance-analytics.yaml
=> Updated status to stable

specification/ambulance-analytics.yaml
=> Improve diagram explanation

manifest_template.yml
Remove need to register callback url in developer hub
=> AMB-1175: remove need for callback url from dev hub

specification/ambulance-analytics.yaml
=> Polaris AMP 257 FHIR conformance statement

specification/ambulance-analytics.yaml
=> Polaris - conformance statement

specification/ambulance-analytics.yaml
=> additional full stop

specification/ambulance-analytics.yaml
=> AMB-1258: minor spec changes

specification/ambulance-analytics.yaml
=> Misc IOPS fixes to API specs.yaml
